### ISSUE TITLE
Add -lib switch to read only sources without modifying them

### ISSUE THREAD

**Issue by th-sabik** [rokath/trice#154]
If a library is used from several projects the IDs inside the lib should not be changeable.
In case of duclicate IDs change inside -src but never inside -lib.
If lib contains dupilcate IDs an error message is needed.

**Comment by rokath** [comment]
Merged with #291

**Comment by rokath** [comment]
See CLI switch -renew when working on this.

**Comment by rokath** [comment]
Running `trice -z` as post-build command keeps the source code without IDs.

**Comment by rokath** [comment]
Not needed, if the `noids` branch is finished.

**Comment by rokath** [comment]
not needed with `trice i` && `trice z`
