### ISSUE TITLE
Add target timestamps as compiler switch

### ISSUE THREAD

**Issue by rokath** [rokath/trice#212]
- The timestamps are with parameter bitwidth or 32 bit?
- The trice tool could use a heuristic or be forced for displaying or suppressing the target timestamps.
- The timestamp formatstring is a command line switch.
- The timestamps are displaying only at trice line start.

**Comment by rokath** [comment]
A bit in the ID space or in the cycle counter space could be used.

**Comment by rokath** [comment]
Rico had the right idea: #214

**Comment by th-sabik** [comment]
Done
