### ISSUE TITLE
TRICE in TRICE not possible!

### ISSUE THREAD

**Issue by rokath** [rokath/trice#247]
- No-Good Example:
```C
int f0( void ){ TRICE( "msg:f0\n"); return 0; }
void f1( void ){ TRICE "No; %d", f0() ); }
```
- This will compile normally but corrupt TRICE output in deferred mode.
- Should work in immediate mode,but does not. Needs further investigation. (Stacksize?)
- Good Workaround:
```C
int f0( void ){ TRICE( "msg:f0\n"); return 0; }
void f1( void ){ int x = f0(); TRICE "Yes: %d", x ); }
```

**Comment by th-sabik** [comment]
Cannot work either in immediate mode.

**Comment by th-sabik** [comment]
Added to the Trice User Guide.
