### ISSUE TITLE
trice update changes line endings of entire file

### ISSUE THREAD

**Issue by liborw** [rokath/trice#251]
**Describe the bug**
`trice update` changes line endings of entire file

**To Reproduce**

```sh
$ file Core/Src/main.c 
Core/Src/main.c: C source, ASCII text, with CRLF line terminators
$ trice update
Read ID List file /home/libor/Personal/learn/trice/til.json with 11 items.
#define TRICE_FILE Id(34120) inserted into main.c
$ file Core/Src/main.c
Core/Src/main.c: C source, ASCII text, with CRLF, LF line terminators
```

**Expected behavior**
The line endings will stay the same.

**Desktop (please complete the following information):**

- OS: archlinux
- Version: latest master (trice-git v0.18.4.r703.g8b91772b-3)

**Comment by rokath** [comment]
This is as expected. The **trice** tool reads files line ending agnostic, but writes files according to the OS. I guess a vice versa behaviour you described in Windows. If this is a real issue, please open the issue again.

**Comment by liborw** [comment]
Actually the problem is that CubeMX generates windows line endings on whatever OS. It might be better to write same line ends as it reads...

**Comment by rokath** [comment]
If you prefer to work with Windows line endings in Linux, you could use dos2linux before and linux2dos after  you activated `trice update` in a script. Other option: use dos2linux after CubeMX code generator.
