### ISSUE TITLE
KPIs 

### ISSUE THREAD

**Issue by madmax440** [rokath/trice#259]
**Is your feature request related to a problem? Please describe.**
How fast is trice? how did you measure that its faster than a regular printf?

**Describe the solution you'd like**
A performance analysis such as latency between the call and return would be nice.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by rokath** [comment]
Please read [TriceSpeed.md](https://github.com/rokath/trice/blob/master/docs/TriceSpeed.md) and [this](https://github.com/rokath/trice/blob/master/docs/TriceVsPrintfSimilaritiesAndDifferences.md#1-printf-like-functions).
