### ISSUE TITLE
Add `-binaryLogfile` option

### ISSUE THREAD

**Issue by th-sabik** [rokath/trice#267]
*Trice* logs could be stored also in binary form. This is now already possible using JLinkRTTLogger. But if a serial port is used the user has to find an own solution now. Binary logs are displayable by the **trice** tool using `trice log -port FILEBUFFER -args name`. They are much shorter than the text log files and more flexible to use. By this option the normal logfile functionality is not affected.

**Comment by th-sabik** [comment]
done in v0.51.0

**Comment by rokath** [comment]
Write doc and Tests for it.

**Comment by rokath** [comment]
Done
