### ISSUE TITLE
trice.c:101 -Wsign-compare

### ISSUE THREAD

**Issue by ypearson** [rokath/trice#273]
warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  101 |     for( unsigned i = 0; i < len; i++ ){

**Comment by rokath** [comment]
Did you mean the code line 101 in `trice.c`:
```C
//! TriceBlockingWrite returns after buf was complketely written.
void TriceBlockingWrite( uint8_t const * buf, unsigned len ){
    for( unsigned i = 0; i < len; i++ ){ 
        triceBlockingPutChar( buf[i] ); }
}
```
I cannot see a problem here. The only thing I could do is to write `= 0u` insteda of `= 0`. Pleas claryfy.

**Comment by rokath** [comment]
Seams to be invalid. Please reopen just in case.
