### ISSUE TITLE
CHANGELOG.md not up to date

### ISSUE THREAD

**Issue by escherstair** [rokath/trice#277]
File [CHANGELOG.md](https://github.com/rokath/trice/blob/master/CHANGELOG.md) lists all the releases until 0.48.0, but two more recent releases are available [here](https://github.com/rokath/trice/releases) ([v0.49.0](https://github.com/rokath/trice/releases/tag/v0.49.0) and [v0.49.1](https://github.com/rokath/trice/releases/tag/v0.49.1)).

I don't know if it's useful having a CHANGELOG.md file;
maybe it can be deleted.

**Comment by rokath** [comment]
Done. Thanks.
