### ISSUE TITLE
trice tool doesn't handle '\t'

### ISSUE THREAD

**Issue by escherstair** [rokath/trice#282]
In C source code I use `\t` when I need to send a `tab` character.
As an example
`TRICE("\tVersion %d.%d.%d", 2, 3, 0);`
When I use the provided trice tool (under Windows 10), the `\t` is shown as character `\` followed by character `t`
![immagine](https://user-images.githubusercontent.com/22594460/167574406-2defe4b6-663d-4735-a1d2-9181a88aa83a.png)
and not as a `TAB` (as in a standard RS232 terminal connected to tjhe UART).

More or less the same issue happens when in the C string I need to put a single `\` character.
In C, the `\` must be escped and so I need to write `\\` when I need to "see" a single `\` in the printed string.
Even in this case, the trice tool shows two backslashes `\\`

Is this expected?
Thanks in advance.

**Comment by rokath** [comment]
That is new for me. `\n` works. I need to investigate that. Did you had a look at the til.json for the `\t`? The strings there are the ones **Go** gets for displaying. I guess I forgot to handle `\t` in the  `update` code. Right now I am very short of time but I will solve that.

**Comment by rokath** [comment]
Seems not to be a big issue: [https://stackoverflow.com/questions/59952721/how-to-read-t-as-tab-in-golang](https://stackoverflow.com/questions/59952721/how-to-read-t-as-tab-in-golang).

**Comment by rokath** [comment]
done in main
