### ISSUE TITLE
TRICE_S macro clarification

### ISSUE THREAD

**Issue by escherstair** [rokath/trice#283]
I need a clarification on the usage of `TRICE_S` macro.
I see [this paragraph](https://github.com/rokath/trice/blob/master/docs/TriceUserGuide.md#dynamic-stringsbuffers-only-as-variable-inside-trice-macros) and as far as I understand, it means "No string literals as arguments inside TRICE macro".
Is this the meaning of the title "Dynamic strings/buffers only as variable inside TRICE macros"? (Sorry, but English is not my native language).
I see that this is a No-Good example
- No-Good Example:
```C
void f0( void ){ TRICE_S( "msg:%s\n", "Hello" ); }
```
and a workaround i suggested.

But, isn't the following one (in [paragraph 5](https://github.com/rokath/trice/blob/master/docs/TriceUserGuide.md#5-adapt-your-legacy-source-code)) the same as No-Good example?
runtime generated strings: Each needs its own `TRICE_S` macro: `TRICE_S( Id(11223), "Entered name is %20s\n", "Paul" );`

Moreover, is it possible to trnasform the workaround into this?
```C
void f0( void ){ const char* s = "Hello"; TRICE_S( "msg:%s\n", s ); }
```
Trying to follow the C best practise "const-qualify everything".

**Comment by rokath** [comment]
The example with "Paul" is wrong. It needs correction.  Your proposal  concerning const is from the C language point totally correct.  But if the strings known at compile time,  they should get a part of the format strings.

**Comment by escherstair** [comment]
I think now I better understand.

All the string literals (i.e. compile-time know strings) should be put inside the format string.
Only the dynamic strings should be used as variables in `TRICE_S` macro.

As an example:
```C
char dynamic_string[50];
fillDynamicStringFromSomewhere(dynamic_string);
TRICE_S( "msg:This part of the string is known at compile time. This part is dynamic %s\n", dynamic_string); 
```

@rokath Can you confirm this is the right usage?
Thanks in advance for all you support.

**Comment by rokath** [comment]
That's perfekt! I will take that in the doc.

**Comment by rokath** [comment]
done in main
