### ISSUE TITLE
Define TRICE_OFF in a single point

### ISSUE THREAD

**Issue by escherstair** [rokath/trice#390]
[Here](https://github.com/rokath/trice/blob/master/docs/TriceUserGuide.md#10-target-side-trice-on-off) I read that adding

> you can add #define TRICE_OFF just before the #include "trice.h" line and no trice code is generated anymore for that file

But this means that I have to add `#define TRICE_OFF` to every file where I included `trice.h`
Would be possible having a way to define `TRICE_OFF` for the whole project?
As an example, passing `TRICE_OFF` definition to the preprocesso with an option?
GCC uses `-D` as described [here](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html) but every toolchain has its own way.

**Comment by rokath** [comment]
Good point, but `-D TRICE _OFF` seems to be a general possible way, as far as I know.

**Comment by escherstair** [comment]
Based on my preliminary test, it seems that it works

**Comment by rokath** [comment]
It is now in the [user manual](https://github.com/rokath/trice/blob/master/docs/TriceUserGuide.md#10-target-side-trice-on-off). Thanks for the hint.

**Comment by rokath** [comment]
Can we close this?

**Comment by escherstair** [comment]
yes
