### ISSUE TITLE
Create function call macros for TRICE_S and its relatives

### ISSUE THREAD

**Issue by th-sabik** [rokath/trice#429]
Possible syntax:
`triceS` , `TriceS`, `TRiceS`
`triceN` , `TriceN`, `TRiceN`
`trice8B` , `Trice8B`, `TRice8B`
`trice16B` , `Trice16B`, `TRice16B`
`trice32B` , `Trice32B`, `TRice32B`
`triceB` , `TriceB`, `TRiceB`
`trice8F` , `Trice8F`, `TRice8F`
`trice16F` , `Trice16F`, `TRice16F`
`trice32F` , `Trice32F`, `TRice32F`
`triceF` , `TriceF`, `TRiceF`

**Comment by KammutierSpule** [comment]
I'm experience that using TRICE_S dumps the macro code directly in the code as is not optimizing it for size.
So I'm also looking to use function calls for TRICE_S (and others) too.

**Comment by rokath** [comment]
This is not implemented yet.

**Comment by rokath** [comment]
Implemented in branch "issue_#429"
