### ISSUE TITLE
error: macro "TRICE32_1" requires 3 arguments, but only 2 given

### ISSUE THREAD

**Issue by KammutierSpule** [rokath/trice#452]
**Describe the bug**
ct2401.cpp:51:8: error: macro "TRICE32_1" requires 3 arguments, but only 2 given
   51 |         TRice( iD(5720), "😴\n" );

if I change it to "😴 %d\n", 0 );
it builds and I can trace on logs.

**Additional context**

compiling with Zephyr, c++ file.

**Comment by rokath** [comment]
Please read https://github.com/rokath/trice/issues/279. I guess you need to change your compiler settings or to use `TRice0` as workaround.

**Comment by KammutierSpule** [comment]
Yes, that is related, and this
https://github.com/rokath/trice/issues/432#issuecomment-2028209322
helped me to fix on a C file.

However, I noticed that the problem seems to be related with other included files.

CONCAT and other defines are messing with the build.

**Comment by rokath** [comment]
The information you provided is not sufficient for me for an action. How to deal further with this issue?
