### ISSUE TITLE
Question: Is possible to use TRICE_N and TRICE_S without sending an id?

### ISSUE THREAD

**Issue by KammutierSpule** [rokath/trice#461]
Or the ID must be sent on every record?

**Comment by rokath** [comment]
https://github.com/rokath/trice/blob/master/test/testdata/triceCheck.c contains examples in lines 108 and 109. **Yes, the ID ist needed.** But you can mix trice data with user data. Have a look into  https://github.com/rokath/trice/blob/master/docs/TriceUserGuide.md#15-binary-encoding.

**Comment by rokath** [comment]
You wrote: "I'm experience that using TRICE_S dumps the macro code directly in the code as is not optimizing it for size.
So I'm also looking to use function calls for TRICE_S (and others) too."

That is a TO DO. Please Check #429.
