### ISSUE TITLE
triceType 0, falls on case TRICE_TYPE_X0

### ISSUE THREAD

**Issue by KammutierSpule** [rokath/trice#463]
Somehow, I'm getting triceType = 0 here:
```
#if TRICE_BUFFER == TRICE_RING_BUFFER
TriceIDAndBuffer
int triceType = TID >> 14;
case TRICE_TYPE_X0:

```
What could be the cause? Could be some of my Trice iDs be missing?

However, after it gets TRICE_TYPE_X0, the code will crash because "unsigned offset;" was not assigned and *pWordCount will result on a random value, resulting on invalid addresses later

**Comment by rokath** [comment]
The reason for that are invalid data. See #462 for more details. I close this now, because it is the same issue as #462.
