### ISSUE TITLE
SingleTricesRingCount multi task protection on TriceTransfer function

### ISSUE THREAD

**Issue by KammutierSpule** [rokath/trice#486]
SingleTricesRingCount is protected by TRICE_ENTER_CRITICAL_SECTION
but on TriceTransfer function, SingleTricesRingCount--; is not protected.

It could happen that the variable is accessed at same time.

Should this be guarded too?

**Comment by rokath** [comment]
> Should this be guarded too?

YES! It is now part of the master branch. Thanks!
